### ISSUE TITLE
Example (2) seems to be off

### ISSUE THREAD

**Issue by semisimple** [movewp3/kafka-compoundkey-serde#5]
Dear colleagues,

thank you for your hard work.
Sadly I ran into issues when following the provided examples:

-  Setting the serializer as proposed to the nested class leads to a KafkaException due to IllegalAccess:
`props.put("key.serializer", serde.serializer().getClass().getName());`

- The serializer does handle CompoundKeys. The Example (1) does implement CompoundKeyProvider (and not CompoundKey). Therefore the key is not to be produced without any call of toCompoundKey. 

I got around this by using a delegation pattern.
In total this looks to me like a (public) Serializer for CompoundKeyProviders is missing?

Best regards and thank you

Robert

**Comment by ginkel** [comment]
Hi Robert,

thanks for your feedback. Handling `CompoundKey`s instead of `CompoundKeyProvider`s is an explicit design intention to avoid having to deserialize the POJO implementing `CompoundKeyProvider`, which is what we wanted to avoid in the first place.

I'll have a look at the `IllegalAccessException`. Can you share a stacktrace?

Thanks,
Thilo

**Comment by semisimple** [comment]
Hello Thilo,

sorry for not providing the stack trace in the first place.
Nevertheless I think you found the source yourself 
and your adjustments will do the trick.

Thank you,

Robert

**Comment by ginkel** [comment]
Hi Robert,

can you verify that

```
<dependency>
  <groupId>io.dwpbank.movewp3</groupId>
  <artifactId>kafka-compoundkey-serde</artifactId>
  <version>0.9.1-SNAPSHOT</version>
</dependency>
```

fixes your problem. If so, we'll roll a new release containing the fix.

Thanks,
Thilo

**Comment by semisimple** [comment]
Hi Thilo,

yes it did solve my issues. I can delete my delegation class and use the shipped serializer.

- [x] No IllegalAccess Exception when using Serializer as advertised
- [x] Example calls toComposeKey()

Thanks again and looking forward for the new release,

Robert

side note:
One could still use the class name (previously used in the example).
`props.put("key.serializer","io.dwpbank.movewp3.kafka.compoundkey.CompoundKeySerde$CompoundKeySerializer");`
 Either way it is working now.
